'use client';

import { useEffect, useRef, useState } from 'react';
import {
  AlertTriangle, Archive, ArrowLeft, ArrowRight, BarChart3, Bell, Check, CheckCircle2, ChevronDown,
  CircleHelp, ClipboardCheck, Clock3, Download, FileCheck2, FileSearch, FileText, Filter,
  Gavel, History, Inbox, LayoutDashboard, ListFilter, LockKeyhole, Menu, Plus, Search, ShieldAlert,
  ShieldCheck, SlidersHorizontal, TableProperties, UploadCloud, UserRound, Users, X,
} from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { bidders, initialAudit, requirements as fixtureRequirements, tender } from '@/lib/demo-data';
import type { AuditEvent, Bidder, Finding, OfficerDecision, Requirement, ResultStatus, View } from '@/lib/domain';

const statusOrder: ResultStatus[] = ['PASS','FAIL','MISSING','REVIEW','UNVERIFIED'];
const processSteps = ['Validating files','Extracting text','Identifying tender requirements','Matching bidder evidence','Applying deterministic rules','Checking inconsistencies','Preparing evidence matrix'];
const viewTitles: Record<View,string> = { welcome:'Welcome', dashboard:'Procurement Dashboard', registry:'Tender Registry', setup:'New Evaluation', requirements:'Requirement Confirmation', processing:'Evaluation in progress', comparison:'Compliance Matrix', bidder:'Bidder Evaluation', review:'Review Queue', decision:'Officer Decision', audit:'Audit Log', reports:'Reports' };
const navItems: Array<{view:View;label:string;icon:typeof LayoutDashboard}> = [
  {view:'dashboard',label:'Dashboard',icon:LayoutDashboard},{view:'registry',label:'Tender Registry',icon:Archive},{view:'setup',label:'New Evaluation',icon:FileText},{view:'requirements',label:'Bidder Evaluations',icon:ClipboardCheck},{view:'comparison',label:'Compliance Matrix',icon:TableProperties},{view:'review',label:'Review Queue',icon:Inbox},{view:'audit',label:'Audit Log',icon:History},{view:'reports',label:'Reports',icon:BarChart3},
];

function statusClass(status: ResultStatus) { return `status status-${status.toLowerCase()}`; }
function StatusBadge({status}:{status:ResultStatus}) {
  const label:Record<ResultStatus,string>={PASS:'Pass',FAIL:'Fail',MISSING:'Missing',REVIEW:'Review',UNVERIFIED:'Unverified'};
  const Icon=status==='PASS'?CheckCircle2:status==='FAIL'?X:status==='MISSING'?FileSearch:status==='REVIEW'?AlertTriangle:Clock3;
  return <span className={statusClass(status)}><Icon size={12}/>{label[status]}</span>;
}
function fmtTime(value:string) { return new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)); }

function Brand({ inverse=false }: { inverse?:boolean }) {
  return <div className={`app-brand ${inverse?'inverse':''}`}><span className="app-brand-icon"><FileCheck2 size={20}/></span><span>The HelpGeM<small>PROCUREMENT EVIDENCE TRAIL</small></span></div>;
}

function Welcome({ onDemo, onNew }: { onDemo:()=>void; onNew:()=>void }) {
  return <main className="welcome-shell">
    <header className="welcome-nav"><Brand/><nav aria-label="Portal navigation"><button onClick={onDemo}>Dashboard</button><button onClick={onDemo}>Tenders</button><button onClick={onDemo}>Bid evaluations</button><button onClick={onDemo}>Reports</button><button onClick={onDemo}>Audit log</button></nav><div className="welcome-profile"><button aria-label="Help" onClick={onDemo}><CircleHelp size={18}/></button><button aria-label="Notifications" onClick={onDemo}><Bell size={18}/></button><div className="officer-avatar">EO</div><span><strong>Evaluation Officer</strong><small>Procurement Division</small></span></div></header>
    <section className="welcome-grid">
      <div className="welcome-copy"><p className="eyebrow">Smart India Hackathon 2026 | SIH26100</p><h1>AI-Assisted Bid Compliance Verification</h1><p>The HelpGeM helps procurement officers examine tender conditions, verify bidder documents and review every recommendation with source-level evidence.</p><p className="welcome-tagline">Every bid. Every clause. Every proof.</p><div className="welcome-actions"><button className="primary-action" onClick={onDemo}>Launch Demo Evaluation <ArrowRight size={18}/></button><button className="secondary-action" onClick={onNew}>Start New Evaluation</button></div><div className="boundary-note"><ShieldCheck size={18}/><span>Decision-support prototype. Final procurement decisions remain with the authorized officer.</span></div></div>
      <div className="evidence-preview"><div className="preview-top"><span>Document verification preview</span><span>Page 03</span></div><div className="doc-sheet"><div className="document-heading"><FileCheck2 size={18}/><span>Financial eligibility review</span></div><dl><div><dt>Requirement</dt><dd>Average annual turnover ≥ ₹5 crore</dd></div><div className="evidence-highlight"><dt>Evidence</dt><dd>“Average turnover: ₹4.2 crore”</dd></div><div><dt>Evidence source</dt><dd>Audited_Balance_Sheet.pdf</dd></div></dl><div className="verdict-card"><div><span>Status</span><strong>Review required</strong></div><b>Conflicting values found across financial documents.</b></div></div></div>
    </section>
    <footer className="welcome-footer"><span>SIH Prototype • Simulated Data • Not an official GeM portal</span></footer>
  </main>;
}

function DropZone({ label, files, onFiles }: { label:string; files:string[]; onFiles:(names:string[])=>void }) {
  const input = useRef<HTMLInputElement>(null);
  const [drag,setDrag] = useState(false);
  const [error,setError] = useState('');
  const add = (list:FileList|null) => {
    if (!list) return;
    const next:string[]=[];
    for (const file of Array.from(list)) {
      if (file.type !== 'application/pdf') { setError(`${file.name}: unsupported file type. PDF only.`); continue; }
      if (file.size === 0) { setError(`${file.name}: empty or corrupt file.`); continue; }
      if (files.includes(file.name) || next.includes(file.name)) { setError(`${file.name}: duplicate document ignored.`); continue; }
      next.push(file.name);
    }
    if (next.length) { setError(''); onFiles([...files,...next]); }
  };
  return <div><button type="button" className={`drop-zone ${drag?'dragging':''}`} onClick={()=>input.current?.click()} onDragOver={(e)=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={(e)=>{e.preventDefault();setDrag(false);add(e.dataTransfer.files)}}><UploadCloud size={25}/><strong>{label}</strong><span>Drag PDF here or click to browse · max 25 MB</span><input ref={input} hidden type="file" accept="application/pdf" multiple onChange={(e)=>add(e.target.files)}/></button>{error&&<p className="field-error"><AlertTriangle size={14}/>{error}</p>}{files.map(file=><div className="uploaded-file" key={file}><FileText size={16}/><span>{file}</span><b><CheckCircle2 size={14}/> Ready</b><button aria-label={`Remove ${file}`} onClick={()=>onFiles(files.filter(f=>f!==file))}><X size={14}/></button></div>)}</div>;
}

function Dashboard({ go, openCase }: { go:(view:View)=>void; openCase:(id:string)=>void }) {
  const metrics: Array<{label:string;value:string;meta:string;Icon:typeof FileText;tone:string}> = [
    {label:'Active Tenders',value:'06',meta:'+2 this month',Icon:FileText,tone:'blue'},
    {label:'Bidders Evaluated',value:'31',meta:'Across 9 categories',Icon:Users,tone:'cyan'},
    {label:'Pending Review',value:'04',meta:'2 high-risk cases',Icon:ShieldAlert,tone:'amber'},
    {label:'Completed Evaluations',value:'18',meta:'94% within SLA',Icon:CheckCircle2,tone:'green'},
  ];
  const cases=[
    {title:'Conflicting turnover values',meta:'Bharat Safety · R1',tone:'review',bidder:'bharat'},
    {title:'Missing OEM authorization',meta:'SecureTech · R5',tone:'missing',bidder:'securetech'},
    {title:'External GST verification unavailable',meta:'Upload evaluation · R3',tone:'unverified',bidder:''},
    {title:'Prompt-injection warning',meta:'SecureTech · Technical Offer p.4',tone:'review',bidder:'securetech'},
  ];
  return <div className="page-stack"><div className="page-heading"><div><h1>Procurement Dashboard</h1><p>Monitor active tenders, bidder evaluations and cases requiring officer review.</p></div><button className="btn primary" onClick={()=>go('setup')}><Plus size={17}/>New Evaluation</button></div>
    <section className="metric-grid">{metrics.map(({label,value,meta,Icon,tone})=><article className="metric-card" key={label}><div className={`metric-icon ${tone}`}><Icon size={20}/></div><span>{label}</span><strong>{value}</strong><small>{meta}</small></article>)}</section>
    <section className="dash-grid"><article className="panel recent-panel"><div className="panel-head"><div><h2>Recent Tender Evaluations</h2><p>Current procurement compliance activity</p></div><button className="text-button" onClick={()=>go('registry')}>View all tenders <ArrowRight size={15}/></button></div><div className="table-scroll"><table><thead><tr><th>Tender ID</th><th>Tender Title</th><th>Closing Date</th><th>Bidders</th><th>Current Status</th><th>Action</th></tr></thead><tbody><tr><td><strong>{tender.id}</strong></td><td>{tender.title}</td><td>30 Sep 2026</td><td>3</td><td><span className="status status-review">Review required</span></td><td><button className="table-link" onClick={()=>go('comparison')}>Open evaluation</button></td></tr><tr><td><strong>GEM/2026/B/10442</strong></td><td>Supply of Fire Retardant Uniforms</td><td>18 Oct 2026</td><td>5</td><td><span className="status status-unverified">In progress</span></td><td><button className="table-link" onClick={()=>go('registry')}>View tender</button></td></tr><tr><td><strong>GEM/2026/B/09918</strong></td><td>Portable Gas Detection Systems</td><td>02 Sep 2026</td><td>4</td><td><span className="status status-pass">Completed</span></td><td><button className="table-link" onClick={()=>go('reports')}>View report</button></td></tr></tbody></table></div></article>
      <article className="review-queue"><div className="section-heading"><div><h2>Review Queue</h2><p>Cases awaiting officer attention</p></div><button className="text-button" onClick={()=>go('review')}>View all</button></div>{cases.map(item=><div className="review-case" key={item.title}><span className={`case-icon ${item.tone}`}><AlertTriangle size={15}/></span><div><strong>{item.title}</strong><small>{item.meta}</small></div><button onClick={()=>item.bidder?openCase(item.bidder):go('setup')}>View case</button></div>)}</article></section>
  </div>;
}

const registryRows = [
  {id:tender.id,title:tender.title,department:'Procurement Division',closing:'30 Sep 2026',bidders:3,progress:'100%',status:'Review required',tone:'review'},
  {id:'GEM/2026/B/10442',title:'Supply of Fire Retardant Uniforms',department:'Safety & Stores',closing:'18 Oct 2026',bidders:5,progress:'72%',status:'In progress',tone:'unverified'},
  {id:'GEM/2026/B/09918',title:'Portable Gas Detection Systems',department:'Industrial Safety',closing:'02 Sep 2026',bidders:4,progress:'100%',status:'Completed',tone:'pass'},
  {id:'GEM/2026/B/10611',title:'Emergency Eye Wash Stations',department:'Plant Operations',closing:'26 Oct 2026',bidders:0,progress:'0%',status:'Draft',tone:'missing'},
];

function TenderRegistry({go}:{go:(v:View)=>void}) {
  const [query,setQuery]=useState(''); const [page,setPage]=useState(1);
  const filtered=registryRows.filter(row=>`${row.id} ${row.title}`.toLowerCase().includes(query.toLowerCase()));
  const pages=Math.max(1,Math.ceil(filtered.length/2));
  const rows=filtered.slice((page-1)*2,page*2);
  return <div className="page-stack"><div className="page-heading"><div><h1>Tender Registry</h1><p>Search and manage procurement evaluations in the prototype environment.</p></div><div className="heading-actions"><button className="btn secondary" onClick={()=>window.print()}><Download size={16}/>Export</button><button className="btn primary" onClick={()=>go('setup')}><Plus size={16}/>New Tender</button></div></div><div className="registry-tools"><label className="search-box"><Search size={17}/><input aria-label="Search tenders" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search by tender ID or description"/></label><button className="btn secondary" onClick={()=>{setQuery('Supply');setPage(1)}}><ListFilter size={16}/>Filter</button></div><section className="panel registry-table"><div className="table-scroll"><table><thead><tr><th>Tender ID</th><th>Tender Description</th><th>Department</th><th>Closing Date</th><th>Bidders</th><th>Evaluation Progress</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.id}</strong></td><td>{row.title}</td><td>{row.department}</td><td>{row.closing}</td><td>{row.bidders}</td><td aria-label={`Evaluation progress ${row.progress}`}><div className="progress-cell"><span><i style={{width:row.progress}}/></span><b>{row.progress}</b></div></td><td><span className={`status status-${row.tone}`}>{row.status}</span></td><td><button className="table-link" onClick={()=>row.id===tender.id?go('comparison'):go('dashboard')}>View</button></td></tr>)}</tbody></table></div><div className="pagination"><span>Showing {rows.length} of {filtered.length} tenders</span><div><button aria-label="Previous tender page" disabled={page===1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><b>{page} / {pages}</b><button aria-label="Next tender page" disabled={page===pages} onClick={()=>setPage(p=>Math.min(pages,p+1))}>Next</button></div></div></section></div>;
}

function ReviewQueue({openCase,go}:{openCase:(id:string)=>void;go:(v:View)=>void}) {
  return <div className="page-stack"><div className="page-heading"><div><h1>Review Queue</h1><p>Evidence conflicts, missing documents and integrity indicators requiring officer attention.</p></div></div><section className="panel registry-table"><div className="table-scroll"><table><thead><tr><th>Priority</th><th>Case</th><th>Bidder</th><th>Requirement</th><th>Reason</th><th>Action</th></tr></thead><tbody><tr><td><span className="status status-review">High</span></td><td>RVW-0261</td><td>Bharat Safety Solutions Ltd.</td><td>R1 · Turnover</td><td>Conflicting values across two financial documents</td><td><button className="table-link" onClick={()=>openCase('bharat')}>Review evidence</button></td></tr><tr><td><span className="status status-missing">Medium</span></td><td>RVW-0262</td><td>SecureTech Equipment LLP</td><td>R5 · OEM authorization</td><td>Mandatory evidence not found</td><td><button className="table-link" onClick={()=>openCase('securetech')}>Review evidence</button></td></tr><tr><td><span className="status status-review">Medium</span></td><td>RVW-0263</td><td>SecureTech Equipment LLP</td><td>Integrity signal</td><td>Instruction-like text detected and ignored</td><td><button className="table-link" onClick={()=>openCase('securetech')}>Review signal</button></td></tr><tr><td><span className="status status-unverified">Normal</span></td><td>RVW-0264</td><td>New upload</td><td>R3 · GST certificate</td><td>External verification unavailable</td><td><button className="table-link" onClick={()=>go('setup')}>Open evaluation</button></td></tr></tbody></table></div></section></div>;
}

function Reports({go}:{go:(v:View)=>void}) {
  return <div className="page-stack"><div className="page-heading"><div><h1>Reports</h1><p>Evaluation records prepared for officer review and printing.</p></div><button className="btn primary" onClick={()=>window.print()}><Download size={16}/>Export Current Report</button></div><section className="report-list"><article><FileText size={22}/><div><strong>Bid Compliance Evaluation Report</strong><span>{tender.id} · 3 bidders · Updated 4 Sep 2026</span></div><button className="table-link" onClick={()=>go('comparison')}>Open report</button></article><article><History size={22}/><div><strong>Audit Trail Report</strong><span>Uploads, confirmations, warnings and officer decisions</span></div><button className="table-link" onClick={()=>go('audit')}>Open report</button></article></section></div>;
}

function Setup({ go, toast }: { go:(view:View)=>void; toast:(s:string)=>void }) {
  const [tenderFiles,setTenderFiles]=useState<string[]>([]); const [bidderFiles,setBidderFiles]=useState<Record<string,string[]>>({Bidder_1:[]}); const [names,setNames]=useState<Record<string,string>>({Bidder_1:''});
  const addBidder=()=>{const key=`Bidder_${Object.keys(bidderFiles).length+1}`;setBidderFiles({...bidderFiles,[key]:[]});setNames({...names,[key]:''});};
  const continueUpload=()=>{toast('Upload saved. Extraction services are not configured; new files will remain UNVERIFIED.');go('requirements')};
  return <div className="page-stack"><div className="page-heading"><div><p className="kicker">NEW EVALUATION</p><h1>Set up tender evaluation</h1><p>Upload searchable PDFs. Document content is always treated as untrusted evidence.</p></div><button className="btn secondary" onClick={()=>go('requirements')}><FileSearch size={17}/>Use demo documents</button></div>
    <div className="setup-grid"><section className="panel form-panel"><div className="section-number"><span>01</span><div><h2>Tender details</h2><p>Core information for the evaluation record</p></div></div><div className="form-grid"><label className="wide">Tender title<input defaultValue="" placeholder="e.g. Supply of industrial safety equipment"/></label><label>Tender / reference ID<input placeholder="GEM/2026/B/00000"/></label><label>Bid-closing date<input type="date"/></label><label className="wide">Procurement category<select defaultValue=""><option value="" disabled>Select a category</option><option>Goods</option><option>Services</option><option>Industrial safety equipment</option></select></label></div><DropZone label="Tender / ATC documents" files={tenderFiles} onFiles={setTenderFiles}/><div className="service-note"><LockKeyhole size={17}/><div><strong>Local upload mode</strong><span>PDFs are validated locally. OCR and AI extraction are not configured, so extracted claims remain UNVERIFIED.</span></div></div></section>
      <section className="panel form-panel"><div className="section-number"><span>02</span><div><h2>Bidder documents</h2><p>Add one or more bidders and their evidence</p></div></div>{Object.keys(bidderFiles).map((key,index)=><div className="bidder-upload" key={key}><div className="bidder-title"><span>{String(index+1).padStart(2,'0')}</span><input value={names[key]} onChange={e=>setNames({...names,[key]:e.target.value})} placeholder={`Bidder ${index+1} legal name`}/></div><DropZone label="Bidder PDF documents" files={bidderFiles[key]} onFiles={files=>setBidderFiles({...bidderFiles,[key]:files})}/></div>)}<button className="add-row" onClick={addBidder}><Plus size={17}/>Add another bidder</button></section></div><div className="sticky-actions"><button className="btn secondary" onClick={()=>go('dashboard')}>Cancel</button><button className="btn primary" onClick={continueUpload}>Save and review requirements <ArrowRight size={17}/></button></div>
  </div>;
}

function Requirements({ go, addAudit, toast }: { go:(view:View)=>void; addAudit:(e:AuditEvent)=>void; toast:(s:string)=>void }) {
  const [rules,setRules]=useState<Requirement[]>(fixtureRequirements); const [confirmed,setConfirmed]=useState<string[]>([]);
  const all=confirmed.length===rules.length;
  const update=(id:string,key:keyof Requirement,value:string|boolean)=>setRules(rules.map(r=>r.id===id?{...r,[key]:value}:r));
  const confirm=(id:string)=>setConfirmed(c=>c.includes(id)?c.filter(x=>x!==id):[...c,id]);
  const run=()=>{if(!all){toast('Confirm all eight requirements before evaluation.');return;} addAudit({id:crypto.randomUUID(),timestamp:new Date().toISOString(),actor:'Evaluation Officer',type:'REQUIREMENT_EDIT',detail:'All 8 extracted requirements reviewed and confirmed.'});go('processing')};
  return <div className="page-stack"><div className="page-heading"><div><p className="kicker">{tender.id}</p><h1>Confirm extracted requirements</h1><p>Review every rule before it becomes part of the deterministic evaluation.</p></div><div className="confirmation-count"><strong>{confirmed.length}/8</strong><span>confirmed</span></div></div><div className="source-banner"><FileText size={19}/><div><strong>{tender.title}</strong><span>Tender_ATC.pdf · 18 pages · Searchable PDF</span></div><b>EXTRACTED</b></div>
    <section className="rule-list">{rules.map(req=><article className={`rule-card ${confirmed.includes(req.id)?'confirmed':''}`} key={req.id}><div className="rule-id"><strong>{req.id}</strong><span>{req.mandatory?'MANDATORY':'OPTIONAL'}</span></div><div className="rule-main"><input className="rule-title-input" aria-label={`${req.id} title`} value={req.title} onChange={e=>update(req.id,'title',e.target.value)}/><textarea aria-label={`${req.id} rule`} value={req.rule} onChange={e=>update(req.id,'rule',e.target.value)}/><div className="rule-fields"><label>Check type<select value={req.checkType} onChange={e=>update(req.id,'checkType',e.target.value)}><option>{req.checkType}</option><option>Numeric threshold</option><option>Document presence</option><option>Date validation</option><option>Normalized exact match</option></select></label><label>Operator<input value={req.operator} onChange={e=>update(req.id,'operator',e.target.value)}/></label><label>Threshold<input value={req.threshold} onChange={e=>update(req.id,'threshold',e.target.value)}/></label><label>Unit<input value={req.unit} onChange={e=>update(req.id,'unit',e.target.value)}/></label></div><div className="citation"><FileSearch size={15}/><span>{req.sourceClause}</span><b>{req.document} · PAGE {String(req.page).padStart(2,'0')}</b></div></div><label className="confirm-check"><input type="checkbox" checked={confirmed.includes(req.id)} onChange={()=>confirm(req.id)}/><span><Check size={16}/></span><small>{confirmed.includes(req.id)?'Confirmed':'Confirm rule'}</small></label></article>)}</section><div className="sticky-actions"><span>{all?'Ready to evaluate 3 bidders':'Every rule must be confirmed'}</span><button className="btn primary" onClick={run} disabled={!all}>Run bidder evaluation <ArrowRight size={17}/></button></div>
  </div>;
}

function Processing({ go, addAudit }: { go:(view:View)=>void; addAudit:(e:AuditEvent)=>void }) {
  const [step,setStep]=useState(0);
  useEffect(()=>{const timer=setInterval(()=>setStep(s=>{if(s>=processSteps.length-1){clearInterval(timer);return s}return s+1}),430);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(step===processSteps.length-1){const t=setTimeout(()=>{addAudit({id:crypto.randomUUID(),timestamp:new Date().toISOString(),actor:'HelpGeM Engine',type:'EVALUATION',detail:'24 deterministic checks completed. 2 findings require officer review.'});go('comparison')},700);return()=>clearTimeout(t)}},[step,go,addAudit]);
  return <div className="processing-page"><div className="processing-visual"><div className="scan-line"/><FileSearch size={42}/><span>24</span></div><p className="kicker">DETERMINISTIC EVALUATION</p><h1>Building the evidence matrix</h1><p>Each bidder claim is being matched to a confirmed clause and its cited source.</p><div className="process-list">{processSteps.map((label,index)=><div className={index<step?'done':index===step?'active':''} key={label}><span>{index<step?<Check size={15}/>:index+1}</span><strong>{label}</strong><b>{index<step?'Complete':index===step?'In progress':'Waiting'}</b></div>)}</div><small>No external AI service is used in this demo.</small></div>;
}

function SummaryCard({ bidder, onOpen }: { bidder:Bidder; onOpen:()=>void }) {
  const pass=bidder.findings.filter(f=>f.status==='PASS').length;
  return <article className="bidder-summary"><div className="bidder-initial">{bidder.shortName.slice(0,2).toUpperCase()}</div><div className="bidder-summary-title"><strong>{bidder.name}</strong><span>{pass} of 8 requirements passed</span></div><div className="recommendation"><span>Recommendation</span><b className={`rec-${bidder.recommendation.toLowerCase().replaceAll(' ','-')}`}>{bidder.recommendation}</b></div><div className="risk"><span>Risk</span><b className={`risk-${bidder.risk.toLowerCase()}`}>{bidder.risk}</b></div><button className="icon-btn" onClick={onOpen} aria-label={`Open ${bidder.name}`}><ArrowRight size={17}/></button></article>;
}

function Comparison({ go, openEvidence, selectBidder }: { go:(v:View)=>void; openEvidence:(b:Bidder,f:Finding)=>void; selectBidder:(b:Bidder)=>void }) {
  const [filter,setFilter]=useState<ResultStatus|'ALL'>('ALL');
  const visible=fixtureRequirements.filter(req=>filter==='ALL'||bidders.some(b=>b.findings.find(f=>f.requirementId===req.id)?.status===filter));
  return <div className="page-stack"><div className="page-heading"><div><span className="record-id">{tender.id} · Evaluation complete</span><h1>Compliance Matrix</h1><p>Compare bidder evidence against each confirmed tender requirement.</p></div><button className="btn secondary" onClick={()=>window.print()}><Download size={17}/>Export Report</button></div><div className="result-strip"><CheckCircle2 size={19}/><span>24 deterministic checks completed</span><b>21 Pass</b><b>2 Review</b><b>1 Missing</b></div>
    <section className="summary-list">{bidders.map(b=><SummaryCard key={b.id} bidder={b} onOpen={()=>{selectBidder(b);go('bidder')}}/>)}</section>
    <section className="panel matrix-panel"><div className="panel-head"><div><h2>Bidder requirement comparison</h2><p>Select a result to inspect its document and page-level evidence.</p></div><div className="filter-row"><Filter size={15}/>{(['ALL',...statusOrder] as const).map(s=><button className={filter===s?'active':''} onClick={()=>setFilter(s)} key={s}>{s==='ALL'?'All':s==='FAIL'?'Failed':s==='REVIEW'?'Review required':s.charAt(0)+s.slice(1).toLowerCase()}</button>)}</div></div><div className="table-scroll"><table className="matrix"><thead><tr><th>Requirement</th>{bidders.map(b=><th key={b.id}>{b.shortName}<small>{b.recommendation}</small></th>)}</tr></thead><tbody>{visible.map(req=><tr key={req.id}><td><b>{req.id}</b><span><strong>{req.title}</strong><small>{req.sourceClause} · p.{req.page}</small></span></td>{bidders.map(b=>{const f=b.findings.find(x=>x.requirementId===req.id)!;return <td key={b.id}><button aria-label={`Open ${b.shortName} evidence for ${req.id}`} className="matrix-result" onClick={()=>openEvidence(b,f)}><StatusBadge status={f.status}/><small>{f.extractedValues.map(e=>e.value).join(' / ')||'No evidence'}</small></button></td>})}</tr>)}</tbody></table></div></section><div className="boundary-footer"><ShieldCheck size={17}/><span>Decision support only. Final procurement decisions remain with the authorized officer.</span><button onClick={()=>go('decision')}>Record Officer Decision <ArrowRight size={15}/></button></div>
  </div>;
}

function BidderDetail({ bidder, go, openEvidence }: { bidder:Bidder; go:(v:View)=>void; openEvidence:(b:Bidder,f:Finding)=>void }) {
  const [expanded,setExpanded]=useState<string[]>([]); const [tab,setTab]=useState<'findings'|'documents'|'signals'>('findings'); const pass=bidder.findings.filter(f=>f.status==='PASS').length;
  const documents=Array.from(new Map(bidder.findings.flatMap(f=>f.extractedValues).map(e=>[e.document,e])).values());
  return <div className="page-stack"><button className="back-button" onClick={()=>go('comparison')}><ArrowLeft size={16}/>Back to comparison</button><section className="bidder-hero"><div className="bidder-initial large">{bidder.shortName.slice(0,2).toUpperCase()}</div><div><span className="bidder-id">Bidder ID · BD-{bidder.id.toUpperCase()}-2026</span><h1>{bidder.name}</h1></div><div className="hero-metrics"><div><span>Compliance recommendation</span><strong>{bidder.recommendation}</strong></div><div><span>Risk level</span><strong className={`risk-${bidder.risk.toLowerCase()}`}>{bidder.risk}</strong></div><div><span>Officer decision</span><strong>Pending</strong></div><button className="btn primary" onClick={()=>go('decision')}>Record Decision</button></div></section><section className="progress-panel"><div><strong>{Math.round(pass/8*100)}%</strong><span>evaluation progress</span></div><div className="big-progress"><span style={{width:`${pass/8*100}%`}}/></div><p>{bidder.findings.filter(f=>f.status!=='PASS').length} outstanding review item(s)</p></section><div className="detail-tabs" role="tablist"><button className={tab==='findings'?'active':''} onClick={()=>setTab('findings')}>Compliance Findings</button><button className={tab==='documents'?'active':''} onClick={()=>setTab('documents')}>Documents <span>{documents.length}</span></button><button className={tab==='signals'?'active':''} onClick={()=>setTab('signals')}>Integrity Signals <span>{bidder.warnings.length}</span></button></div>
    {tab==='signals'&&(bidder.warnings.length>0?<section className="security-panel"><div className="security-head"><ShieldAlert size={22}/><div><h2>Document integrity indicator detected</h2><p>Indicators require officer review; they are not conclusions of tampering or fraud.</p></div></div>{bidder.warnings.map(w=><div className="security-warning" key={w.title}><div><strong>{w.title}</strong><q>{w.detectedText}</q></div><div><span>{w.document} · Page {w.page}</span><b>{w.action}</b><em>{w.recommendation}</em></div></div>)}</section>:<section className="empty-section"><ShieldCheck size={22}/><strong>No integrity signals recorded</strong><span>No suspicious document indicators were found in the controlled evidence set.</span></section>)}
    {tab==='documents'&&<section className="panel registry-table"><div className="table-scroll"><table><thead><tr><th>Document</th><th>Evidence pages</th><th>Extraction status</th><th>Action</th></tr></thead><tbody>{documents.map(doc=><tr key={doc.document}><td><strong>{doc.document}</strong></td><td>Page {doc.page}</td><td><span className="status status-pass">Extracted</span></td><td><button className="table-link" onClick={()=>{const f=bidder.findings.find(item=>item.extractedValues.some(e=>e.document===doc.document));if(f)openEvidence(bidder,f)}}>View evidence</button></td></tr>)}</tbody></table></div></section>}
    {tab==='findings'&&<section className="panel finding-panel"><div className="panel-head"><div><h2>Compliance Findings</h2><p>Clause-by-clause evaluation with traceable evidence</p></div></div>{bidder.findings.map(f=><article className="finding-row" key={f.requirementId}><button className="finding-summary" onClick={()=>setExpanded(x=>x.includes(f.requirementId)?x.filter(i=>i!==f.requirementId):[...x,f.requirementId])}><b>{f.requirementId}</b><div><strong>{fixtureRequirements.find(r=>r.id===f.requirementId)?.title}</strong><span>{f.reason}</span></div><span className={statusClass(f.status)}>{f.status}</span><ChevronDown size={17}/></button>{expanded.includes(f.requirementId)&&<div className="finding-detail"><div><span>Required value</span><strong>{f.requiredValue}</strong></div><div><span>Extracted value</span><strong>{f.extractedValues.map(e=>e.value).join(' / ')||'Not found'}</strong></div><div><span>Evidence source</span><strong>{f.extractedValues[0]?`${f.extractedValues[0].document} · p.${f.extractedValues[0].page}`:'No source evidence'}</strong></div><button className="btn secondary" onClick={()=>openEvidence(bidder,f)}>View Evidence</button></div>}</article>)}</section>}
  </div>;
}

function Decision({ selected, decisions, save, go, toast }: { selected:Bidder; decisions:OfficerDecision[]; save:(d:OfficerDecision)=>void; go:(v:View)=>void; toast:(s:string)=>void }) {
  const [bidderId,setBidderId]=useState(selected.id); const [choice,setChoice]=useState<OfficerDecision['decision']|' '>(' '); const [reason,setReason]=useState(''); const [open,setOpen]=useState(false); const bidder=bidders.find(b=>b.id===bidderId)!; const prior=decisions.find(d=>d.bidderId===bidderId);
  const review=()=>{if(choice===' '||reason.trim().length<10){toast('Select a decision and enter a reason of at least 10 characters.');return;}setOpen(true)};
  const confirm=()=>{if(choice===' ')return;save({bidderId,decision:choice,reason:reason.trim(),officer:'Evaluation Officer',timestamp:new Date().toISOString()});setOpen(false);toast('Officer decision saved to the audit trail.');go('audit')};
  const options:Array<{value:OfficerDecision['decision'];label:string;help:string}>=[{value:'Qualified',label:'Qualify',help:'Proceed to the next authorized procurement stage.'},{value:'Disqualified',label:'Disqualify',help:'Record that confirmed conditions were not met.'},{value:'Send for Clarification',label:'Request Clarification',help:'Request specific additional evidence from the bidder.'}];
  return <div className="page-stack decision-wrap"><div className="page-heading"><div><h1>Officer Decision</h1><p>Review the system recommendation and evidence before recording an authorized decision.</p></div></div><section className="decision-grid"><div className="panel decision-form"><label>Select bidder<select value={bidderId} onChange={e=>setBidderId(e.target.value)}>{bidders.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><div className="system-rec"><span>System recommendation</span><strong>{bidder.recommendation}</strong><small>Risk level: {bidder.risk}</small></div><fieldset><legend>Officer decision</legend>{options.map(option=><label className={choice===option.value?'selected':''} key={option.value}><input type="radio" name="decision" checked={choice===option.value} onChange={()=>setChoice(option.value)}/><span>{option.value==='Qualified'?<CheckCircle2/>:option.value==='Disqualified'?<X/>:<Clock3/>}</span><div><strong>{option.label}</strong><small>{option.help}</small></div></label>)}</fieldset><label>Written reason <span className="required">Required</span><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain the evidence considered and the basis for this decision…"/><small>{reason.length} characters · minimum 10</small></label><button className="btn primary full" onClick={review}>Review Decision <ArrowRight size={17}/></button></div><aside className="panel decision-context"><h2>Evidence summary</h2><div className="decision-stat"><span>Clear passes</span><b>{bidder.findings.filter(f=>f.status==='PASS').length}</b></div><div className="decision-stat"><span>Outstanding review items</span><b>{bidder.findings.filter(f=>f.status==='REVIEW').length}</b></div><div className="decision-stat"><span>Missing evidence</span><b>{bidder.findings.filter(f=>f.status==='MISSING').length}</b></div>{prior&&<div className="prior-decision"><History size={17}/><div><strong>Prior decision: {prior.decision}</strong><span>{fmtTime(prior.timestamp)}</span></div></div>}<div className="officer-card"><UserRound size={20}/><div><strong>Evaluation Officer</strong><span>Procurement Division</span><small>{fmtTime(new Date().toISOString())}</small></div></div></aside></section>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="confirm-modal"><DialogHeader><div className="modal-icon"><Gavel/></div><DialogTitle>Confirm officer decision</DialogTitle><DialogDescription>This action records the officer’s decision in the audit log.</DialogDescription></DialogHeader><div className="confirm-summary"><span>{bidder.name}</span><strong>{choice}</strong><p>“{reason}”</p></div><DialogFooter><button className="btn secondary" onClick={()=>setOpen(false)}>Go back</button><button className="btn primary" onClick={confirm}>Confirm and Save</button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function Audit({ audit }: { audit:AuditEvent[] }) {
  const [filter,setFilter]=useState<'ALL'|AuditEvent['type']>('ALL'); const visible=filter==='ALL'?audit:audit.filter(e=>e.type===filter);
  const bidderFor=(event:AuditEvent)=>bidders.find(b=>event.detail.includes(b.name))?.shortName??'—';
  return <div className="page-stack"><div className="page-heading"><div><h1>Audit Log</h1><p>Timestamped record of uploads, rule confirmations, evaluations, warnings and officer decisions.</p></div><button className="btn primary" onClick={()=>window.print()}><Download size={17}/>Export Audit Log</button></div><section className="audit-summary"><ShieldCheck size={22}/><div><strong>Audit record complete</strong><span>{audit.length} events · Last updated {fmtTime(audit[audit.length-1]?.timestamp||new Date().toISOString())}</span></div><b>Traceable record</b></section><section className="panel audit-panel"><div className="panel-head"><div><h2>Evaluation events</h2><p>{tender.id}</p></div><label className="select-inline"><SlidersHorizontal size={15}/><select aria-label="Filter audit events" value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="ALL">All events</option><option value="UPLOAD">Upload</option><option value="REQUIREMENT_EDIT">Rule confirmation</option><option value="EVALUATION">Evaluation</option><option value="WARNING">Warning</option><option value="DECISION">Final decision</option></select></label></div><div className="table-scroll"><table className="audit-table"><thead><tr><th>Timestamp</th><th>Actor</th><th>Event</th><th>Tender</th><th>Bidder</th><th>Previous Value</th><th>New Value</th><th>Reason</th></tr></thead><tbody>{visible.map(event=><tr key={event.id}><td>{fmtTime(event.timestamp)}</td><td>{event.actor}</td><td><span className={`status audit-event audit-${event.type.toLowerCase()}`}>{event.type.replace('_',' ')}</span></td><td>{tender.id}</td><td>{bidderFor(event)}</td><td>—</td><td>{event.type==='DECISION'?'Decision recorded':event.type==='REQUIREMENT_EDIT'?'Rules confirmed':'—'}</td><td>{event.detail}</td></tr>)}</tbody></table></div></section></div>;
}

function EvidenceDrawer({ data, close }: { data:{bidder:Bidder;finding:Finding}|null; close:()=>void }) {
  const [sourceOpen,setSourceOpen]=useState(false);
  const req=data?fixtureRequirements.find(r=>r.id===data.finding.requirementId):null;
  return <Sheet open={Boolean(data)} onOpenChange={(o)=>{if(!o){setSourceOpen(false);close()}}}><SheetContent className="evidence-drawer"><SheetHeader><SheetTitle>Compliance Evidence</SheetTitle><SheetDescription>{req?.id} · {req?.title} · {data?.bidder.name}</SheetDescription></SheetHeader>{data&&req&&<div className="drawer-body"><div className="drawer-verdict"><span className={statusClass(data.finding.status)}>{data.finding.status}</span><div><strong>Explanation</strong><p>{data.finding.reason}</p></div></div><section><h3>Tender clause</h3><blockquote>{req.rule}</blockquote><div className="citation"><FileText size={15}/><span>{req.sourceClause}</span><b>{req.document} · Page {req.page}</b></div></section><section><h3>Required and extracted values</h3><div className="compare-box"><div><span>Required</span><strong>{data.finding.requiredValue}</strong></div><ArrowRight/><div><span>Extracted</span><strong>{data.finding.extractedValues.map(e=>e.value).join(' / ')||'Evidence not found'}</strong></div></div></section><section><h3>Evidence source</h3>{data.finding.extractedValues.length?data.finding.extractedValues.map((e,index)=><div className="evidence-page" key={`${e.document}-${index}`}><div className="paper-head"><FileText size={17}/><span>{e.document}</span><b>Page {String(e.page).padStart(2,'0')}</b></div><q>{e.evidence}</q>{sourceOpen&&<p className="source-context">Verified demo excerpt from {e.document}, page {e.page}. The cited text is shown exactly as stored in the controlled evidence fixture.</p>}<div><span>Extraction confidence</span><strong>{Math.round(e.confidence*100)}%</strong><button onClick={()=>setSourceOpen(!sourceOpen)}>{sourceOpen?'Close source page':'Open source page'}</button></div></div>):<div className="empty-evidence"><Search size={25}/><strong>No source evidence found</strong><span>No page citation has been generated.</span></div>}</section><div className="drawer-boundary"><ShieldCheck size={17}/><span>Evidence supports officer review. It does not make the final procurement decision.</span></div></div>}</SheetContent></Sheet>;
}

export default function HelpGemApp() {
  const [view,setView]=useState<View>('welcome'); const [selected,setSelected]=useState<Bidder>(bidders[0]); const [evidence,setEvidence]=useState<{bidder:Bidder;finding:Finding}|null>(null); const [audit,setAudit]=useState<AuditEvent[]>(initialAudit); const [decisions,setDecisions]=useState<OfficerDecision[]>(()=>{if(typeof window==='undefined')return [];try{const stored=localStorage.getItem('helpgem-decisions');return stored?JSON.parse(stored) as OfficerDecision[]:[]}catch{return []}}); const [toast,setToast]=useState(''); const [mobileNav,setMobileNav]=useState(false);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(t)},[toast]);
  const addAudit=(event:AuditEvent)=>setAudit(a=>[...a,event]);
  const save=(decision:OfficerDecision)=>{setDecisions(d=>{const next=[...d.filter(x=>x.bidderId!==decision.bidderId),decision];localStorage.setItem('helpgem-decisions',JSON.stringify(next));return next});addAudit({id:crypto.randomUUID(),timestamp:decision.timestamp,actor:decision.officer,type:'DECISION',detail:`Final decision for ${bidders.find(b=>b.id===decision.bidderId)?.name}: ${decision.decision}. Reason: ${decision.reason}`})};
  const go=(next:View)=>{setView(next);setMobileNav(false);window.scrollTo({top:0,behavior:'smooth'})};
  const openCase=(id:string)=>{const bidder=bidders.find(item=>item.id===id);if(bidder)setSelected(bidder);go('bidder')};
  useEffect(()=>{
    type Tool = { name:string; title:string; description:string; inputSchema:object; annotations:Record<string,boolean>; execute:(input:unknown)=>unknown };
    type ModelContext = { registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void> };
    const context=(document as Document & {modelContext?:ModelContext}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    const register=(tool:Tool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined)}catch{/* Unsupported draft implementation. */}};
    register({name:'open_demo_evaluation',title:'Open HelpGeM demo evaluation',description:'Open the built-in SIH tender and its three bidder comparison results.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{go('comparison');return{tenderId:tender.id,bidders:bidders.length,status:'opened'}}});
    register({name:'record_officer_decision',title:'Record officer decision',description:'Record a final human decision for one demo bidder with a mandatory written reason.',inputSchema:{type:'object',properties:{bidderId:{type:'string',enum:bidders.map(b=>b.id)},decision:{type:'string',enum:['Qualified','Disqualified','Send for Clarification']},reason:{type:'string',minLength:10}},required:['bidderId','decision','reason'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input)=>{const value=input as Partial<OfficerDecision>;if(!bidders.some(b=>b.id===value.bidderId)||!['Qualified','Disqualified','Send for Clarification'].includes(value.decision??'')||(value.reason?.trim().length??0)<10)throw new Error('A valid bidder, decision, and reason of at least 10 characters are required.');const decision:OfficerDecision={bidderId:value.bidderId!,decision:value.decision as OfficerDecision['decision'],reason:value.reason!.trim(),officer:'Evaluation Officer',timestamp:new Date().toISOString()};save(decision);go('audit');return{bidderId:decision.bidderId,decision:decision.decision,status:'recorded'}}});
    return()=>lifecycle.abort();
  },[]);
  if(view==='welcome')return <Welcome onDemo={()=>go('dashboard')} onNew={()=>go('setup')}/>;
  const content = view==='dashboard'?<Dashboard go={go} openCase={openCase}/>:view==='registry'?<TenderRegistry go={go}/>:view==='setup'?<Setup go={go} toast={setToast}/>:view==='requirements'?<Requirements go={go} addAudit={addAudit} toast={setToast}/>:view==='processing'?<Processing go={go} addAudit={addAudit}/>:view==='comparison'?<Comparison go={go} openEvidence={(bidder,finding)=>setEvidence({bidder,finding})} selectBidder={setSelected}/>:view==='bidder'?<BidderDetail bidder={selected} go={go} openEvidence={(bidder,finding)=>setEvidence({bidder,finding})}/>:view==='review'?<ReviewQueue openCase={openCase} go={go}/>:view==='decision'?<Decision selected={selected} decisions={decisions} save={save} go={go} toast={setToast}/>:view==='reports'?<Reports go={go}/>:<Audit audit={audit}/>;
  return <div className="app-shell"><div className="portal-utility"><span>SIH26100 — AI-Powered Bid Compliance Verification</span><span>SIH Prototype • Simulated Data • Not an official GeM portal</span></div><header className="topbar"><button className="menu-btn" onClick={()=>setMobileNav(true)} aria-label="Open navigation"><Menu/></button><Brand/><nav className="header-nav"><button className={view==='dashboard'?'active':''} onClick={()=>go('dashboard')}>Dashboard</button><button className={view==='registry'?'active':''} onClick={()=>go('registry')}>Tenders</button><button className={['requirements','comparison','bidder','review'].includes(view)?'active':''} onClick={()=>go('comparison')}>Bid Evaluations</button><button className={view==='reports'?'active':''} onClick={()=>go('reports')}>Reports</button><button className={view==='audit'?'active':''} onClick={()=>go('audit')}>Audit Log</button></nav><div className="topbar-right"><button className="header-icon" aria-label="Help" onClick={()=>setToast('Help guide is available in the project README.')}><CircleHelp size={18}/></button><button className="header-icon notification" aria-label="Notifications" onClick={()=>go('review')}><Bell size={18}/><i/></button><button className="officer-avatar" title="Simulated officer account">EO</button><div className="officer-name"><strong>Evaluation Officer</strong><span>Procurement Division</span></div></div></header><aside className={`sidebar ${mobileNav?'open':''}`}><div className="sidebar-top"><span>Procurement workspace</span><button className="mobile-close" aria-label="Close navigation" onClick={()=>setMobileNav(false)}><X/></button></div><nav>{navItems.map(({view:v,label,icon:Icon})=><button className={view===v||(view==='bidder'&&v==='comparison')?'active':''} onClick={()=>go(v)} key={v}><Icon size={18}/>{label}{v==='review'&&<span className="nav-count">4</span>}</button>)}</nav><div className="sidebar-bottom"><div className="guardrail"><ShieldCheck size={18}/><div><strong>Decision support</strong><span>Officer remains in control</span></div></div><button onClick={()=>go('welcome')}><ArrowLeft size={16}/>Return to welcome</button></div></aside><main className="workspace"><div className="workspace-title"><span>{viewTitles[view]}</span><small>{tender.id}</small></div><div className="workspace-content">{content}</div><footer className="portal-footer">SIH Prototype • Simulated Data • Not an official GeM portal</footer></main>{mobileNav&&<button className="nav-overlay" aria-label="Close navigation" onClick={()=>setMobileNav(false)}/>}<EvidenceDrawer data={evidence} close={()=>setEvidence(null)}/>{toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</div>;
}
